# Generated by Django 6.0.6 on 2026-06-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0028_alter_beneficiary_beneficiary_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
