# Generated by Django 6.0.6 on 2026-06-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0029_delete_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataMigrationLog',
        ),
    ]
